package po;

// Generated 2015-2-28 15:00:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Studytime generated by hbm2java
 */
public class Studytime implements java.io.Serializable {

	private BigDecimal dataId;
	private BigDecimal ayId;
	private String tfcId;
	private String coachId;
	private String stdtId;
	private String carId;
	private String fieldId;
	private String coachIcno;
	private String stdtIcno;
	private String carPzh;
	private String fieldCode;
	private BigDecimal begDay;
	private BigDecimal begMinute;
	private BigDecimal begTime;
	private BigDecimal endTime;
	private String ph;
	private String km;
	private String timeType;
	private String isSim;
	private BigDecimal trMinute;
	private BigDecimal drMinute;
	private BigDecimal maxSpeed;
	private BigDecimal runMile;
	private BigDecimal confirmType;
	private String educationCode;
	private String xgCard;
	private String dataVer;
	private String dataFrom;
	private String dataFromInfo;
	private BigDecimal collectDate;
	private String dataCk1;
	private String dataCk2;
	private String dogNo;
	private String audPass;
	private String audRemark;
	private String hadModify;
	private String cyzgCartype;
	private String deviceId;
	private BigDecimal hddatackver;
	private BigDecimal isOk;
	private String signCode;
	private BigDecimal snsMinute;
	private BigDecimal audModBeg;
	private BigDecimal audModEnd;
	private BigDecimal roomId;
	private String roomType;
	private BigDecimal state;
	private BigDecimal FId;
	private String ip;
	private BigDecimal saveCount;
	private String saveFlag;
	private String sessionId;
	private BigDecimal userId;
	private BigDecimal zid;
	private String zcode;
	private String zname;
	private BigDecimal uploadFlag;
	private String photoIn;
	private String photoOut;

	public Studytime() {
	}

	public Studytime(BigDecimal dataId, BigDecimal state, BigDecimal uploadFlag) {
		this.dataId = dataId;
		this.state = state;
		this.uploadFlag = uploadFlag;
	}

	public Studytime(BigDecimal dataId, BigDecimal ayId, String tfcId,
			String coachId, String stdtId, String carId, String fieldId,
			String coachIcno, String stdtIcno, String carPzh, String fieldCode,
			BigDecimal begDay, BigDecimal begMinute, BigDecimal begTime,
			BigDecimal endTime, String ph, String km, String timeType,
			String isSim, BigDecimal trMinute, BigDecimal drMinute,
			BigDecimal maxSpeed, BigDecimal runMile, BigDecimal confirmType,
			String educationCode, String xgCard, String dataVer,
			String dataFrom, String dataFromInfo, BigDecimal collectDate,
			String dataCk1, String dataCk2, String dogNo, String audPass,
			String audRemark, String hadModify, String cyzgCartype,
			String deviceId, BigDecimal hddatackver, BigDecimal isOk,
			String signCode, BigDecimal snsMinute, BigDecimal audModBeg,
			BigDecimal audModEnd, BigDecimal roomId, String roomType,
			BigDecimal state, BigDecimal FId, String ip, BigDecimal saveCount,
			String saveFlag, String sessionId, BigDecimal userId,
			BigDecimal zid, String zcode, String zname, BigDecimal uploadFlag,
			String photoIn, String photoOut) {
		this.dataId = dataId;
		this.ayId = ayId;
		this.tfcId = tfcId;
		this.coachId = coachId;
		this.stdtId = stdtId;
		this.carId = carId;
		this.fieldId = fieldId;
		this.coachIcno = coachIcno;
		this.stdtIcno = stdtIcno;
		this.carPzh = carPzh;
		this.fieldCode = fieldCode;
		this.begDay = begDay;
		this.begMinute = begMinute;
		this.begTime = begTime;
		this.endTime = endTime;
		this.ph = ph;
		this.km = km;
		this.timeType = timeType;
		this.isSim = isSim;
		this.trMinute = trMinute;
		this.drMinute = drMinute;
		this.maxSpeed = maxSpeed;
		this.runMile = runMile;
		this.confirmType = confirmType;
		this.educationCode = educationCode;
		this.xgCard = xgCard;
		this.dataVer = dataVer;
		this.dataFrom = dataFrom;
		this.dataFromInfo = dataFromInfo;
		this.collectDate = collectDate;
		this.dataCk1 = dataCk1;
		this.dataCk2 = dataCk2;
		this.dogNo = dogNo;
		this.audPass = audPass;
		this.audRemark = audRemark;
		this.hadModify = hadModify;
		this.cyzgCartype = cyzgCartype;
		this.deviceId = deviceId;
		this.hddatackver = hddatackver;
		this.isOk = isOk;
		this.signCode = signCode;
		this.snsMinute = snsMinute;
		this.audModBeg = audModBeg;
		this.audModEnd = audModEnd;
		this.roomId = roomId;
		this.roomType = roomType;
		this.state = state;
		this.FId = FId;
		this.ip = ip;
		this.saveCount = saveCount;
		this.saveFlag = saveFlag;
		this.sessionId = sessionId;
		this.userId = userId;
		this.zid = zid;
		this.zcode = zcode;
		this.zname = zname;
		this.uploadFlag = uploadFlag;
		this.photoIn = photoIn;
		this.photoOut = photoOut;
	}

	public BigDecimal getDataId() {
		return this.dataId;
	}

	public void setDataId(BigDecimal dataId) {
		this.dataId = dataId;
	}

	public BigDecimal getAyId() {
		return this.ayId;
	}

	public void setAyId(BigDecimal ayId) {
		this.ayId = ayId;
	}

	public String getTfcId() {
		return this.tfcId;
	}

	public void setTfcId(String tfcId) {
		this.tfcId = tfcId;
	}

	public String getCoachId() {
		return this.coachId;
	}

	public void setCoachId(String coachId) {
		this.coachId = coachId;
	}

	public String getStdtId() {
		return this.stdtId;
	}

	public void setStdtId(String stdtId) {
		this.stdtId = stdtId;
	}

	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

	public String getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(String fieldId) {
		this.fieldId = fieldId;
	}

	public String getCoachIcno() {
		return this.coachIcno;
	}

	public void setCoachIcno(String coachIcno) {
		this.coachIcno = coachIcno;
	}

	public String getStdtIcno() {
		return this.stdtIcno;
	}

	public void setStdtIcno(String stdtIcno) {
		this.stdtIcno = stdtIcno;
	}

	public String getCarPzh() {
		return this.carPzh;
	}

	public void setCarPzh(String carPzh) {
		this.carPzh = carPzh;
	}

	public String getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(String fieldCode) {
		this.fieldCode = fieldCode;
	}

	public BigDecimal getBegDay() {
		return this.begDay;
	}

	public void setBegDay(BigDecimal begDay) {
		this.begDay = begDay;
	}

	public BigDecimal getBegMinute() {
		return this.begMinute;
	}

	public void setBegMinute(BigDecimal begMinute) {
		this.begMinute = begMinute;
	}

	public BigDecimal getBegTime() {
		return this.begTime;
	}

	public void setBegTime(BigDecimal begTime) {
		this.begTime = begTime;
	}

	public BigDecimal getEndTime() {
		return this.endTime;
	}

	public void setEndTime(BigDecimal endTime) {
		this.endTime = endTime;
	}

	public String getPh() {
		return this.ph;
	}

	public void setPh(String ph) {
		this.ph = ph;
	}

	public String getKm() {
		return this.km;
	}

	public void setKm(String km) {
		this.km = km;
	}

	public String getTimeType() {
		return this.timeType;
	}

	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	public String getIsSim() {
		return this.isSim;
	}

	public void setIsSim(String isSim) {
		this.isSim = isSim;
	}

	public BigDecimal getTrMinute() {
		return this.trMinute;
	}

	public void setTrMinute(BigDecimal trMinute) {
		this.trMinute = trMinute;
	}

	public BigDecimal getDrMinute() {
		return this.drMinute;
	}

	public void setDrMinute(BigDecimal drMinute) {
		this.drMinute = drMinute;
	}

	public BigDecimal getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(BigDecimal maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	public BigDecimal getRunMile() {
		return this.runMile;
	}

	public void setRunMile(BigDecimal runMile) {
		this.runMile = runMile;
	}

	public BigDecimal getConfirmType() {
		return this.confirmType;
	}

	public void setConfirmType(BigDecimal confirmType) {
		this.confirmType = confirmType;
	}

	public String getEducationCode() {
		return this.educationCode;
	}

	public void setEducationCode(String educationCode) {
		this.educationCode = educationCode;
	}

	public String getXgCard() {
		return this.xgCard;
	}

	public void setXgCard(String xgCard) {
		this.xgCard = xgCard;
	}

	public String getDataVer() {
		return this.dataVer;
	}

	public void setDataVer(String dataVer) {
		this.dataVer = dataVer;
	}

	public String getDataFrom() {
		return this.dataFrom;
	}

	public void setDataFrom(String dataFrom) {
		this.dataFrom = dataFrom;
	}

	public String getDataFromInfo() {
		return this.dataFromInfo;
	}

	public void setDataFromInfo(String dataFromInfo) {
		this.dataFromInfo = dataFromInfo;
	}

	public BigDecimal getCollectDate() {
		return this.collectDate;
	}

	public void setCollectDate(BigDecimal collectDate) {
		this.collectDate = collectDate;
	}

	public String getDataCk1() {
		return this.dataCk1;
	}

	public void setDataCk1(String dataCk1) {
		this.dataCk1 = dataCk1;
	}

	public String getDataCk2() {
		return this.dataCk2;
	}

	public void setDataCk2(String dataCk2) {
		this.dataCk2 = dataCk2;
	}

	public String getDogNo() {
		return this.dogNo;
	}

	public void setDogNo(String dogNo) {
		this.dogNo = dogNo;
	}

	public String getAudPass() {
		return this.audPass;
	}

	public void setAudPass(String audPass) {
		this.audPass = audPass;
	}

	public String getAudRemark() {
		return this.audRemark;
	}

	public void setAudRemark(String audRemark) {
		this.audRemark = audRemark;
	}

	public String getHadModify() {
		return this.hadModify;
	}

	public void setHadModify(String hadModify) {
		this.hadModify = hadModify;
	}

	public String getCyzgCartype() {
		return this.cyzgCartype;
	}

	public void setCyzgCartype(String cyzgCartype) {
		this.cyzgCartype = cyzgCartype;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public BigDecimal getHddatackver() {
		return this.hddatackver;
	}

	public void setHddatackver(BigDecimal hddatackver) {
		this.hddatackver = hddatackver;
	}

	public BigDecimal getIsOk() {
		return this.isOk;
	}

	public void setIsOk(BigDecimal isOk) {
		this.isOk = isOk;
	}

	public String getSignCode() {
		return this.signCode;
	}

	public void setSignCode(String signCode) {
		this.signCode = signCode;
	}

	public BigDecimal getSnsMinute() {
		return this.snsMinute;
	}

	public void setSnsMinute(BigDecimal snsMinute) {
		this.snsMinute = snsMinute;
	}

	public BigDecimal getAudModBeg() {
		return this.audModBeg;
	}

	public void setAudModBeg(BigDecimal audModBeg) {
		this.audModBeg = audModBeg;
	}

	public BigDecimal getAudModEnd() {
		return this.audModEnd;
	}

	public void setAudModEnd(BigDecimal audModEnd) {
		this.audModEnd = audModEnd;
	}

	public BigDecimal getRoomId() {
		return this.roomId;
	}

	public void setRoomId(BigDecimal roomId) {
		this.roomId = roomId;
	}

	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	public BigDecimal getState() {
		return this.state;
	}

	public void setState(BigDecimal state) {
		this.state = state;
	}

	public BigDecimal getFId() {
		return this.FId;
	}

	public void setFId(BigDecimal FId) {
		this.FId = FId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public BigDecimal getSaveCount() {
		return this.saveCount;
	}

	public void setSaveCount(BigDecimal saveCount) {
		this.saveCount = saveCount;
	}

	public String getSaveFlag() {
		return this.saveFlag;
	}

	public void setSaveFlag(String saveFlag) {
		this.saveFlag = saveFlag;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	public BigDecimal getZid() {
		return this.zid;
	}

	public void setZid(BigDecimal zid) {
		this.zid = zid;
	}

	public String getZcode() {
		return this.zcode;
	}

	public void setZcode(String zcode) {
		this.zcode = zcode;
	}

	public String getZname() {
		return this.zname;
	}

	public void setZname(String zname) {
		this.zname = zname;
	}

	public BigDecimal getUploadFlag() {
		return this.uploadFlag;
	}

	public void setUploadFlag(BigDecimal uploadFlag) {
		this.uploadFlag = uploadFlag;
	}

	public String getPhotoIn() {
		return this.photoIn;
	}

	public void setPhotoIn(String photoIn) {
		this.photoIn = photoIn;
	}

	public String getPhotoOut() {
		return this.photoOut;
	}

	public void setPhotoOut(String photoOut) {
		this.photoOut = photoOut;
	}

}
