package po;

// Generated 2015-2-28 15:00:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private BigDecimal stdtId;
	private BigDecimal id;
	private BigDecimal tfcId;
	private BigDecimal ayId;
	private BigDecimal sclUnitId;
	private BigDecimal sclDeptId;
	private BigDecimal tfcSId;
	private BigDecimal tfcCId;
	private BigDecimal tfcJId;
	private BigDecimal plcId;
	private BigDecimal plcUnitId;
	private BigDecimal stdtIcno;
	private String icState;
	private String stdtNo;
	private String name;
	private String chsPy;
	private BigDecimal teachCartype;
	private BigDecimal trainRuleVerId;
	private BigDecimal trainRuleId;
	private String drvCartype;
	private String batchCode;
	private Date inDate;
	private String state;
	private Date outDate;
	private String sfzNo;
	private String sfzAreaCode;
	private String sfzAreaAddress;
	private String sfzStreet;
	private String sfzAddress;
	private String linkAddress;
	private String tempAddress;
	private String isLocal;
	private String sex;
	private Date birthday;
	private String nationality;
	private String paperType;
	private String paperNo;
	private String nationType;
	private String knowledge;
	private String zipCode;
	private String workDept;
	private String telMov;
	private String telOth;
	private String isAddDrv;
	private String orgDrvCartype;
	private String orgPlcFileNo;
	private String orgPlcName;
	private Date orgPlcDate;
	private String allowExmNo;
	private String tranNo;
	private String fileNo;
	private String tfcOverNo;
	private Date tfcOverDate;
	private String plcFileNo;
	private Date plcFileDate;
	private String plcFileName;
	private String remark;
	private String pic;
	private String dataFrom;
	private String dataFromInfo;
	private String curPlcStatus;
	private String curTfcStatus;
	private BigDecimal createUnitId;
	private String createUnitName;
	private BigDecimal createUserId;
	private String createUserName;
	private Date createTime;
	private BigDecimal lastmodUnitId;
	private String lastmodUnitName;
	private BigDecimal lastmodUserId;
	private String lastmodUserName;
	private Date lastmodTime;
	private String ssjd;
	private String jwh;
	private String isPrintPxjl;
	private String classType;
	private String origin;
	private BigDecimal uid;
	private String flag;
	private BigDecimal zid;
	private String zcode;
	private String zname;
	private String status;
	private Long abnormalAudTime;
	private Long editCount;

	public Student() {
	}

	public Student(BigDecimal stdtId) {
		this.stdtId = stdtId;
	}

	public Student(BigDecimal stdtId, BigDecimal id, BigDecimal tfcId,
			BigDecimal ayId, BigDecimal sclUnitId, BigDecimal sclDeptId,
			BigDecimal tfcSId, BigDecimal tfcCId, BigDecimal tfcJId,
			BigDecimal plcId, BigDecimal plcUnitId, BigDecimal stdtIcno,
			String icState, String stdtNo, String name, String chsPy,
			BigDecimal teachCartype, BigDecimal trainRuleVerId,
			BigDecimal trainRuleId, String drvCartype, String batchCode,
			Date inDate, String state, Date outDate, String sfzNo,
			String sfzAreaCode, String sfzAreaAddress, String sfzStreet,
			String sfzAddress, String linkAddress, String tempAddress,
			String isLocal, String sex, Date birthday, String nationality,
			String paperType, String paperNo, String nationType,
			String knowledge, String zipCode, String workDept, String telMov,
			String telOth, String isAddDrv, String orgDrvCartype,
			String orgPlcFileNo, String orgPlcName, Date orgPlcDate,
			String allowExmNo, String tranNo, String fileNo, String tfcOverNo,
			Date tfcOverDate, String plcFileNo, Date plcFileDate,
			String plcFileName, String remark, String pic, String dataFrom,
			String dataFromInfo, String curPlcStatus, String curTfcStatus,
			BigDecimal createUnitId, String createUnitName,
			BigDecimal createUserId, String createUserName, Date createTime,
			BigDecimal lastmodUnitId, String lastmodUnitName,
			BigDecimal lastmodUserId, String lastmodUserName, Date lastmodTime,
			String ssjd, String jwh, String isPrintPxjl, String classType,
			String origin, BigDecimal uid, String flag, BigDecimal zid,
			String zcode, String zname, String status, Long abnormalAudTime,
			Long editCount) {
		this.stdtId = stdtId;
		this.id = id;
		this.tfcId = tfcId;
		this.ayId = ayId;
		this.sclUnitId = sclUnitId;
		this.sclDeptId = sclDeptId;
		this.tfcSId = tfcSId;
		this.tfcCId = tfcCId;
		this.tfcJId = tfcJId;
		this.plcId = plcId;
		this.plcUnitId = plcUnitId;
		this.stdtIcno = stdtIcno;
		this.icState = icState;
		this.stdtNo = stdtNo;
		this.name = name;
		this.chsPy = chsPy;
		this.teachCartype = teachCartype;
		this.trainRuleVerId = trainRuleVerId;
		this.trainRuleId = trainRuleId;
		this.drvCartype = drvCartype;
		this.batchCode = batchCode;
		this.inDate = inDate;
		this.state = state;
		this.outDate = outDate;
		this.sfzNo = sfzNo;
		this.sfzAreaCode = sfzAreaCode;
		this.sfzAreaAddress = sfzAreaAddress;
		this.sfzStreet = sfzStreet;
		this.sfzAddress = sfzAddress;
		this.linkAddress = linkAddress;
		this.tempAddress = tempAddress;
		this.isLocal = isLocal;
		this.sex = sex;
		this.birthday = birthday;
		this.nationality = nationality;
		this.paperType = paperType;
		this.paperNo = paperNo;
		this.nationType = nationType;
		this.knowledge = knowledge;
		this.zipCode = zipCode;
		this.workDept = workDept;
		this.telMov = telMov;
		this.telOth = telOth;
		this.isAddDrv = isAddDrv;
		this.orgDrvCartype = orgDrvCartype;
		this.orgPlcFileNo = orgPlcFileNo;
		this.orgPlcName = orgPlcName;
		this.orgPlcDate = orgPlcDate;
		this.allowExmNo = allowExmNo;
		this.tranNo = tranNo;
		this.fileNo = fileNo;
		this.tfcOverNo = tfcOverNo;
		this.tfcOverDate = tfcOverDate;
		this.plcFileNo = plcFileNo;
		this.plcFileDate = plcFileDate;
		this.plcFileName = plcFileName;
		this.remark = remark;
		this.pic = pic;
		this.dataFrom = dataFrom;
		this.dataFromInfo = dataFromInfo;
		this.curPlcStatus = curPlcStatus;
		this.curTfcStatus = curTfcStatus;
		this.createUnitId = createUnitId;
		this.createUnitName = createUnitName;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
		this.createTime = createTime;
		this.lastmodUnitId = lastmodUnitId;
		this.lastmodUnitName = lastmodUnitName;
		this.lastmodUserId = lastmodUserId;
		this.lastmodUserName = lastmodUserName;
		this.lastmodTime = lastmodTime;
		this.ssjd = ssjd;
		this.jwh = jwh;
		this.isPrintPxjl = isPrintPxjl;
		this.classType = classType;
		this.origin = origin;
		this.uid = uid;
		this.flag = flag;
		this.zid = zid;
		this.zcode = zcode;
		this.zname = zname;
		this.status = status;
		this.abnormalAudTime = abnormalAudTime;
		this.editCount = editCount;
	}

	public BigDecimal getStdtId() {
		return this.stdtId;
	}

	public void setStdtId(BigDecimal stdtId) {
		this.stdtId = stdtId;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getTfcId() {
		return this.tfcId;
	}

	public void setTfcId(BigDecimal tfcId) {
		this.tfcId = tfcId;
	}

	public BigDecimal getAyId() {
		return this.ayId;
	}

	public void setAyId(BigDecimal ayId) {
		this.ayId = ayId;
	}

	public BigDecimal getSclUnitId() {
		return this.sclUnitId;
	}

	public void setSclUnitId(BigDecimal sclUnitId) {
		this.sclUnitId = sclUnitId;
	}

	public BigDecimal getSclDeptId() {
		return this.sclDeptId;
	}

	public void setSclDeptId(BigDecimal sclDeptId) {
		this.sclDeptId = sclDeptId;
	}

	public BigDecimal getTfcSId() {
		return this.tfcSId;
	}

	public void setTfcSId(BigDecimal tfcSId) {
		this.tfcSId = tfcSId;
	}

	public BigDecimal getTfcCId() {
		return this.tfcCId;
	}

	public void setTfcCId(BigDecimal tfcCId) {
		this.tfcCId = tfcCId;
	}

	public BigDecimal getTfcJId() {
		return this.tfcJId;
	}

	public void setTfcJId(BigDecimal tfcJId) {
		this.tfcJId = tfcJId;
	}

	public BigDecimal getPlcId() {
		return this.plcId;
	}

	public void setPlcId(BigDecimal plcId) {
		this.plcId = plcId;
	}

	public BigDecimal getPlcUnitId() {
		return this.plcUnitId;
	}

	public void setPlcUnitId(BigDecimal plcUnitId) {
		this.plcUnitId = plcUnitId;
	}

	public BigDecimal getStdtIcno() {
		return this.stdtIcno;
	}

	public void setStdtIcno(BigDecimal stdtIcno) {
		this.stdtIcno = stdtIcno;
	}

	public String getIcState() {
		return this.icState;
	}

	public void setIcState(String icState) {
		this.icState = icState;
	}

	public String getStdtNo() {
		return this.stdtNo;
	}

	public void setStdtNo(String stdtNo) {
		this.stdtNo = stdtNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getChsPy() {
		return this.chsPy;
	}

	public void setChsPy(String chsPy) {
		this.chsPy = chsPy;
	}

	public BigDecimal getTeachCartype() {
		return this.teachCartype;
	}

	public void setTeachCartype(BigDecimal teachCartype) {
		this.teachCartype = teachCartype;
	}

	public BigDecimal getTrainRuleVerId() {
		return this.trainRuleVerId;
	}

	public void setTrainRuleVerId(BigDecimal trainRuleVerId) {
		this.trainRuleVerId = trainRuleVerId;
	}

	public BigDecimal getTrainRuleId() {
		return this.trainRuleId;
	}

	public void setTrainRuleId(BigDecimal trainRuleId) {
		this.trainRuleId = trainRuleId;
	}

	public String getDrvCartype() {
		return this.drvCartype;
	}

	public void setDrvCartype(String drvCartype) {
		this.drvCartype = drvCartype;
	}

	public String getBatchCode() {
		return this.batchCode;
	}

	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	public String getSfzNo() {
		return this.sfzNo;
	}

	public void setSfzNo(String sfzNo) {
		this.sfzNo = sfzNo;
	}

	public String getSfzAreaCode() {
		return this.sfzAreaCode;
	}

	public void setSfzAreaCode(String sfzAreaCode) {
		this.sfzAreaCode = sfzAreaCode;
	}

	public String getSfzAreaAddress() {
		return this.sfzAreaAddress;
	}

	public void setSfzAreaAddress(String sfzAreaAddress) {
		this.sfzAreaAddress = sfzAreaAddress;
	}

	public String getSfzStreet() {
		return this.sfzStreet;
	}

	public void setSfzStreet(String sfzStreet) {
		this.sfzStreet = sfzStreet;
	}

	public String getSfzAddress() {
		return this.sfzAddress;
	}

	public void setSfzAddress(String sfzAddress) {
		this.sfzAddress = sfzAddress;
	}

	public String getLinkAddress() {
		return this.linkAddress;
	}

	public void setLinkAddress(String linkAddress) {
		this.linkAddress = linkAddress;
	}

	public String getTempAddress() {
		return this.tempAddress;
	}

	public void setTempAddress(String tempAddress) {
		this.tempAddress = tempAddress;
	}

	public String getIsLocal() {
		return this.isLocal;
	}

	public void setIsLocal(String isLocal) {
		this.isLocal = isLocal;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getPaperType() {
		return this.paperType;
	}

	public void setPaperType(String paperType) {
		this.paperType = paperType;
	}

	public String getPaperNo() {
		return this.paperNo;
	}

	public void setPaperNo(String paperNo) {
		this.paperNo = paperNo;
	}

	public String getNationType() {
		return this.nationType;
	}

	public void setNationType(String nationType) {
		this.nationType = nationType;
	}

	public String getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(String knowledge) {
		this.knowledge = knowledge;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getWorkDept() {
		return this.workDept;
	}

	public void setWorkDept(String workDept) {
		this.workDept = workDept;
	}

	public String getTelMov() {
		return this.telMov;
	}

	public void setTelMov(String telMov) {
		this.telMov = telMov;
	}

	public String getTelOth() {
		return this.telOth;
	}

	public void setTelOth(String telOth) {
		this.telOth = telOth;
	}

	public String getIsAddDrv() {
		return this.isAddDrv;
	}

	public void setIsAddDrv(String isAddDrv) {
		this.isAddDrv = isAddDrv;
	}

	public String getOrgDrvCartype() {
		return this.orgDrvCartype;
	}

	public void setOrgDrvCartype(String orgDrvCartype) {
		this.orgDrvCartype = orgDrvCartype;
	}

	public String getOrgPlcFileNo() {
		return this.orgPlcFileNo;
	}

	public void setOrgPlcFileNo(String orgPlcFileNo) {
		this.orgPlcFileNo = orgPlcFileNo;
	}

	public String getOrgPlcName() {
		return this.orgPlcName;
	}

	public void setOrgPlcName(String orgPlcName) {
		this.orgPlcName = orgPlcName;
	}

	public Date getOrgPlcDate() {
		return this.orgPlcDate;
	}

	public void setOrgPlcDate(Date orgPlcDate) {
		this.orgPlcDate = orgPlcDate;
	}

	public String getAllowExmNo() {
		return this.allowExmNo;
	}

	public void setAllowExmNo(String allowExmNo) {
		this.allowExmNo = allowExmNo;
	}

	public String getTranNo() {
		return this.tranNo;
	}

	public void setTranNo(String tranNo) {
		this.tranNo = tranNo;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getTfcOverNo() {
		return this.tfcOverNo;
	}

	public void setTfcOverNo(String tfcOverNo) {
		this.tfcOverNo = tfcOverNo;
	}

	public Date getTfcOverDate() {
		return this.tfcOverDate;
	}

	public void setTfcOverDate(Date tfcOverDate) {
		this.tfcOverDate = tfcOverDate;
	}

	public String getPlcFileNo() {
		return this.plcFileNo;
	}

	public void setPlcFileNo(String plcFileNo) {
		this.plcFileNo = plcFileNo;
	}

	public Date getPlcFileDate() {
		return this.plcFileDate;
	}

	public void setPlcFileDate(Date plcFileDate) {
		this.plcFileDate = plcFileDate;
	}

	public String getPlcFileName() {
		return this.plcFileName;
	}

	public void setPlcFileName(String plcFileName) {
		this.plcFileName = plcFileName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public String getDataFrom() {
		return this.dataFrom;
	}

	public void setDataFrom(String dataFrom) {
		this.dataFrom = dataFrom;
	}

	public String getDataFromInfo() {
		return this.dataFromInfo;
	}

	public void setDataFromInfo(String dataFromInfo) {
		this.dataFromInfo = dataFromInfo;
	}

	public String getCurPlcStatus() {
		return this.curPlcStatus;
	}

	public void setCurPlcStatus(String curPlcStatus) {
		this.curPlcStatus = curPlcStatus;
	}

	public String getCurTfcStatus() {
		return this.curTfcStatus;
	}

	public void setCurTfcStatus(String curTfcStatus) {
		this.curTfcStatus = curTfcStatus;
	}

	public BigDecimal getCreateUnitId() {
		return this.createUnitId;
	}

	public void setCreateUnitId(BigDecimal createUnitId) {
		this.createUnitId = createUnitId;
	}

	public String getCreateUnitName() {
		return this.createUnitName;
	}

	public void setCreateUnitName(String createUnitName) {
		this.createUnitName = createUnitName;
	}

	public BigDecimal getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(BigDecimal createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return this.createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getLastmodUnitId() {
		return this.lastmodUnitId;
	}

	public void setLastmodUnitId(BigDecimal lastmodUnitId) {
		this.lastmodUnitId = lastmodUnitId;
	}

	public String getLastmodUnitName() {
		return this.lastmodUnitName;
	}

	public void setLastmodUnitName(String lastmodUnitName) {
		this.lastmodUnitName = lastmodUnitName;
	}

	public BigDecimal getLastmodUserId() {
		return this.lastmodUserId;
	}

	public void setLastmodUserId(BigDecimal lastmodUserId) {
		this.lastmodUserId = lastmodUserId;
	}

	public String getLastmodUserName() {
		return this.lastmodUserName;
	}

	public void setLastmodUserName(String lastmodUserName) {
		this.lastmodUserName = lastmodUserName;
	}

	public Date getLastmodTime() {
		return this.lastmodTime;
	}

	public void setLastmodTime(Date lastmodTime) {
		this.lastmodTime = lastmodTime;
	}

	public String getSsjd() {
		return this.ssjd;
	}

	public void setSsjd(String ssjd) {
		this.ssjd = ssjd;
	}

	public String getJwh() {
		return this.jwh;
	}

	public void setJwh(String jwh) {
		this.jwh = jwh;
	}

	public String getIsPrintPxjl() {
		return this.isPrintPxjl;
	}

	public void setIsPrintPxjl(String isPrintPxjl) {
		this.isPrintPxjl = isPrintPxjl;
	}

	public String getClassType() {
		return this.classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public BigDecimal getUid() {
		return this.uid;
	}

	public void setUid(BigDecimal uid) {
		this.uid = uid;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public BigDecimal getZid() {
		return this.zid;
	}

	public void setZid(BigDecimal zid) {
		this.zid = zid;
	}

	public String getZcode() {
		return this.zcode;
	}

	public void setZcode(String zcode) {
		this.zcode = zcode;
	}

	public String getZname() {
		return this.zname;
	}

	public void setZname(String zname) {
		this.zname = zname;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getAbnormalAudTime() {
		return this.abnormalAudTime;
	}

	public void setAbnormalAudTime(Long abnormalAudTime) {
		this.abnormalAudTime = abnormalAudTime;
	}

	public Long getEditCount() {
		return this.editCount;
	}

	public void setEditCount(Long editCount) {
		this.editCount = editCount;
	}

}
